#define WINDOW_WIDTH 1200
#define WINDOW_HEIGHT 800

#define PLAYER_TEXTURE_FILEPATH "player_texture.png"
#define PLAYER_SCALE 2.f
#define PLAYER_SPEED 500.f

#define WORLD_BOUNDARY_LEFT 200
#define WORLD_BOUNDARY_RIGHT 1000

#define WALL_INITIAL_WIDTH 300.f
#define WALL_SPEED 400.f
#define WALL_INITIAL_SPAWN_TIME 1.f

#define SCORE_FONT_FILEPATH "Audiowide-Regular.ttf"
#define SCORE_TEXT_SIZE 500